on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mantle-register.yml'
      - 'packages/mantle/back/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout master
        uses: actions/checkout@main
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build container image
        run: docker build -f ./packages/mantle/back/Dockerfile -t registry.digitalocean.com/jar-containers/mantle:$(echo $GITHUB_SHA | head -c7) .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/jar-containers/mantle:$(echo $GITHUB_SHA | head -c7)
